# meson/arm-qemu.ini — QEMU Cortex-M4 cross build
[binaries]
c       = 'arm-none-eabi-gcc'
cpp     = 'arm-none-eabi-g++'
ar      = 'arm-none-eabi-ar'
strip   = 'arm-none-eabi-strip'
objcopy = 'arm-none-eabi-objcopy'
size    = 'arm-none-eabi-size'

[host_machine]
system     = 'none'
cpu_family = 'arm'
cpu        = 'cortex-m4'
endian     = 'little'

[built-in options]
c_args   = ['-mcpu=cortex-m4', '-mthumb', '-mfloat-abi=hard', '-mfpu=fpv4-sp-d16']
cpp_args = ['-mcpu=cortex-m4', '-mthumb', '-mfloat-abi=hard', '-mfpu=fpv4-sp-d16']
c_link_args   = ['--specs=rdimon.specs', '-lrdimon', '-lc', '-lm']
cpp_link_args = ['--specs=rdimon.specs', '-lrdimon', '-lc', '-lm']

[project options]
target_platform = 'qemu'
