# meson/arm-stm32f4.ini — real STM32F4 hardware
[binaries]
c       = 'arm-none-eabi-gcc'
cpp     = 'arm-none-eabi-g++'
ar      = 'arm-none-eabi-ar'
strip   = 'arm-none-eabi-strip'
objcopy = 'arm-none-eabi-objcopy'
size    = 'arm-none-eabi-size'

[host_machine]
system     = 'none'
cpu_family = 'arm'
cpu        = 'cortex-m4'
endian     = 'little'

[built-in options]
c_args   = ['-mcpu=cortex-m4', '-mthumb', '-mfloat-abi=hard', '-mfpu=fpv4-sp-d16', '-DCPU_FREQ_HZ=168000000']
cpp_args = ['-mcpu=cortex-m4', '-mthumb', '-mfloat-abi=hard', '-mfpu=fpv4-sp-d16', '-DCPU_FREQ_HZ=168000000']
c_link_args   = ['--specs=nosys.specs', '-lc', '-lm', '-lnosys']
cpp_link_args = ['--specs=nosys.specs', '-lc', '-lm', '-lnosys']

[project options]
target_platform = 'stm32f4'
